train_data_dir: s3://xhs.bravo/user/togo/structure/data/label_importance/train/实体抽取_top15类目_200条_对齐标准_chenzhan1_全部_20210814142511.csv
val_data_dir: s3://xhs.bravo/user/togo/structure/data/label_importance/train/实体抽取_top15类目_200条_对齐标准_chenzhan1_全部_20210814142511.csv
infer_data_dir: s3://xhs.bravo/user/togo/structure/data/label_importance/train/实体抽取_top15类目_200条_对齐标准_chenzhan1_全部_20210814142511.csv
infer_dataset: infer#image#logits#label,name
  #log_dir: s3://xhs.bravo/user/togo/structure/log/label_importance/1/
  #savedmodel_dir: s3://xhs.bravo/user/togo/structure/model/label_importance/1/
  #result_dir: s3://xhs.bravo/user/togo/structure/result/label_importance/1/result.json
log_dir: /home/togo/togo/xhs.bravo/user/togo/structure/log/label_importance/1/
savedmodel_dir: /home/togo/togo/xhs.bravo/user/togo/structure/model/label_importance/1/
result_dir: /home/togo/togo/xhs.bravo/user/togo/structure/result/label_importance/1/result.json
vocab_file: s3://xhs.bravo/user/ut/bert_pretrain/bert-base-chinese-torch/vocab.txt
local_file: /home/togo/togo/xhs.bravo/user/ut/bert_pretrain/bert-base-chinese-torch/vocab.txt
#init_ckpt: /home/togo/togo/xhs.bravo/user/togo/lowquality/log/uncomfortable/21/ckpt-1969
#best_ckpt: /home/togo/togo/xhs.bravo/user/togo/lowquality/log/uncomfortable/27/best/best-ckpt-4

num_classes: 2
epochs: 10
max_ckpt_files_to_keep: 5
steps_logging: 10
steps_saving_ckpt: 100
max_len: 512

learning_rate: 0.01
num_examples: 200

batch_size:
  default: 32
  val: 30
  infer: 128
gpu_list:
  default:
  train: 2
  val: 0
  infer: 0,1
